name: python-lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  checks: write
  contents: write

jobs:
  run-linters:
    name: Trigger Linters
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup Python Env
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: pip install black flake8

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          auto_fix: true
          black: true
          black_auto_fix: true
          flake8: true
          flake8_auto_fix: true